site_name: OS2Datascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

markdown_extensions:
  - sane_lists

nav:
  - Overview: index.md
  - Data sources: data-sources.md
  - Development environment: dev-environment.md
  - Management Commands: management-commands.md
  - The engine:
    - Engine/pipeline: architecture/pipeline.md
    - The model: engine2.md
    - The rule engine: rules.md
  - Security Architecture: architecture/security.md
  - Frontend Architecture: architecture/frontend.md
  - Scan API: api.md
  - Accessing the Microsoft Graph API with graphiti: graphiti.md
  - Deployment:
    - Installation: installation.md
    - Docker: docker.md
    - Configuration: configuration.md
    - Requirements: requirements.md
    - Release procedure: release-procedure.md
    - Microsoft Azure: azure/azure-setup-guide.md
  - Reusable components: reusable-components.md
  - Release notes: changelog.md
