site_name: OS2Datascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

nav:
  - Overview: index.md
  - Development environment: dev-environment.md
  - Management Commands: management-commands.md
  - Engine/pipeline: architecture/pipeline.md
  - Security Architecture: architecture/security.md
  - Frontend Architecture: architecture/frontend.md
  - Scan API: api.md
  - Extending OS2Datascanner: engine2.md
  - Deployment:
    - Installation: installation.md
    - Docker: docker.md
    - Configuration: configuration.md
    - Requirements: requirements.md
    - Release procedure: release-procedure.md
  - Reusable components: reusable-components.md
  - Release notes: changelog.md
